import type { Issue, Comment, EmergencyContact, NationalHotline } from "./types"

export const mockIssues: Issue[] = [
  {
    id: "CL-2024-001",
    title: "Large pothole on Galle Road",
    description: "Deep pothole near the bus stop causing accidents. Multiple vehicles have been damaged. Needs immediate attention.",
    category: "potholes",
    severity: "critical",
    status: "open",
    location: "Galle Road, Colombo 03",
    coordinates: { lat: 6.9147, lng: 79.8563 },
    photos: [],
    upvotes: 142,
    commentCount: 23,
    reporter: "Anonymous",
    isAnonymous: true,
    createdAt: "2026-02-21T07:00:00Z",
    aiConfidence: 95,
    aiCategory: "Pothole",
    severityScore: 9,
    resolutionConfirmations: 0,
  },
  {
    id: "CL-2024-002",
    title: "Broken street light on Duplication Road",
    description: "Street light has been broken for over a week. Area is very dark at night, posing safety risks for pedestrians.",
    category: "streetLights",
    severity: "high",
    status: "in-progress",
    location: "Duplication Road, Colombo 04",
    coordinates: { lat: 6.8935, lng: 79.8587 },
    photos: [],
    upvotes: 89,
    commentCount: 12,
    reporter: "KS",
    isAnonymous: false,
    createdAt: "2026-02-20T14:30:00Z",
    aiConfidence: 88,
    aiCategory: "Street Light",
    severityScore: 7,
    resolutionConfirmations: 0,
  },
  {
    id: "CL-2024-003",
    title: "Garbage pile at Pettah Market",
    description: "Large uncollected garbage pile near the entrance of Pettah Market. Causing severe health hazards and foul smell.",
    category: "garbage",
    severity: "high",
    status: "open",
    location: "Pettah Market, Colombo 11",
    coordinates: { lat: 6.9366, lng: 79.8505 },
    photos: [],
    upvotes: 234,
    commentCount: 45,
    reporter: "Anonymous",
    isAnonymous: true,
    createdAt: "2026-02-19T09:15:00Z",
    aiConfidence: 97,
    aiCategory: "Garbage",
    severityScore: 8,
    resolutionConfirmations: 0,
  },
  {
    id: "CL-2024-004",
    title: "Water pipe leak in Nugegoda",
    description: "Major water pipe leak flooding the road and nearby shops. Clean water being wasted continuously.",
    category: "waterSupply",
    severity: "critical",
    status: "open",
    location: "High Level Road, Nugegoda",
    coordinates: { lat: 6.8722, lng: 79.8897 },
    photos: [],
    upvotes: 178,
    commentCount: 31,
    reporter: "RP",
    isAnonymous: false,
    createdAt: "2026-02-21T03:00:00Z",
    aiConfidence: 91,
    aiCategory: "Water Supply",
    severityScore: 9,
    resolutionConfirmations: 0,
  },
  {
    id: "CL-2024-005",
    title: "Cracked road surface on Marine Drive",
    description: "Multiple cracks on the road surface creating hazardous conditions for motorcyclists and cyclists.",
    category: "roadDamage",
    severity: "medium",
    status: "in-progress",
    location: "Marine Drive, Colombo 06",
    coordinates: { lat: 6.8843, lng: 79.8601 },
    photos: [],
    upvotes: 67,
    commentCount: 8,
    reporter: "AN",
    isAnonymous: false,
    createdAt: "2026-02-18T11:45:00Z",
    aiConfidence: 84,
    aiCategory: "Road Damage",
    severityScore: 5,
    resolutionConfirmations: 0,
  },
  {
    id: "CL-2024-006",
    title: "Blocked drainage at Town Hall junction",
    description: "Drainage system completely blocked causing flooding during rains. Stagnant water breeding mosquitoes.",
    category: "drainage",
    severity: "high",
    status: "open",
    location: "Town Hall, Colombo 07",
    coordinates: { lat: 6.9114, lng: 79.8637 },
    photos: [],
    upvotes: 156,
    commentCount: 19,
    reporter: "Anonymous",
    isAnonymous: true,
    createdAt: "2026-02-17T16:20:00Z",
    aiConfidence: 89,
    aiCategory: "Drainage",
    severityScore: 7,
    resolutionConfirmations: 0,
  },
  {
    id: "CL-2024-007",
    title: "Missing manhole cover near University",
    description: "Dangerous open manhole near Colombo University entrance. Students and pedestrians at risk of falling in.",
    category: "publicSafety",
    severity: "critical",
    status: "open",
    location: "Reid Avenue, Colombo 07",
    coordinates: { lat: 6.9037, lng: 79.8614 },
    photos: [],
    upvotes: 312,
    commentCount: 56,
    reporter: "DM",
    isAnonymous: false,
    createdAt: "2026-02-21T01:00:00Z",
    aiConfidence: 93,
    aiCategory: "Public Safety",
    severityScore: 10,
    resolutionConfirmations: 0,
  },
  {
    id: "CL-2024-008",
    title: "Overflowing garbage bins in Bambalapitiya",
    description: "Multiple garbage bins overflowing for 3 days. Stray animals scattering waste around the area.",
    category: "garbage",
    severity: "medium",
    status: "open",
    location: "Bambalapitiya, Colombo 04",
    coordinates: { lat: 6.8923, lng: 79.8570 },
    photos: [],
    upvotes: 45,
    commentCount: 7,
    reporter: "Anonymous",
    isAnonymous: true,
    createdAt: "2026-02-20T08:00:00Z",
    aiConfidence: 96,
    aiCategory: "Garbage",
    severityScore: 5,
    resolutionConfirmations: 0,
  },
  {
    id: "CL-2024-009",
    title: "Broken sidewalk tiles in Fort area",
    description: "Several sidewalk tiles are broken and uneven, causing tripping hazard for pedestrians especially elderly.",
    category: "roadDamage",
    severity: "low",
    status: "in-progress",
    location: "Fort, Colombo 01",
    coordinates: { lat: 6.9342, lng: 79.8428 },
    photos: [],
    upvotes: 28,
    commentCount: 4,
    reporter: "ML",
    isAnonymous: false,
    createdAt: "2026-02-16T13:30:00Z",
    aiConfidence: 79,
    aiCategory: "Road Damage",
    severityScore: 3,
    resolutionConfirmations: 0,
  },
  {
    id: "CL-2024-010",
    title: "No street lighting on Baseline Road stretch",
    description: "500m stretch of Baseline Road has no working street lights. Area reported to have increase in crime.",
    category: "streetLights",
    severity: "high",
    status: "open",
    location: "Baseline Road, Colombo 09",
    coordinates: { lat: 6.9267, lng: 79.8748 },
    photos: [],
    upvotes: 198,
    commentCount: 34,
    reporter: "Anonymous",
    isAnonymous: true,
    createdAt: "2026-02-15T19:00:00Z",
    aiConfidence: 86,
    aiCategory: "Street Light",
    severityScore: 8,
    resolutionConfirmations: 0,
  },
]

export const mockResolvedIssues: Issue[] = [
  {
    id: "CL-2024-R01",
    title: "Pothole fixed on Havelock Road",
    description: "Large pothole that was causing traffic congestion has been repaired by CMC.",
    category: "potholes",
    severity: "high",
    status: "resolved",
    location: "Havelock Road, Colombo 05",
    photos: [],
    upvotes: 87,
    commentCount: 15,
    reporter: "TK",
    isAnonymous: false,
    createdAt: "2026-02-10T10:00:00Z",
    resolvedAt: "2026-02-18T14:00:00Z",
    resolvedBy: "community",
    severityScore: 7,
  },
  {
    id: "CL-2024-R02",
    title: "Garbage cleared at Wellawatte Beach",
    description: "Beach area cleanup completed by municipal workers after community reporting.",
    category: "garbage",
    severity: "medium",
    status: "resolved",
    location: "Wellawatte Beach, Colombo 06",
    photos: [],
    upvotes: 124,
    commentCount: 22,
    reporter: "Anonymous",
    isAnonymous: true,
    createdAt: "2026-02-08T07:30:00Z",
    resolvedAt: "2026-02-14T11:00:00Z",
    resolvedBy: "official",
    severityScore: 5,
  },
  {
    id: "CL-2024-R03",
    title: "Street lights restored on Bauddhaloka Mawatha",
    description: "All 12 broken street lights along Bauddhaloka Mawatha have been replaced.",
    category: "streetLights",
    severity: "high",
    status: "resolved",
    location: "Bauddhaloka Mawatha, Colombo 07",
    photos: [],
    upvotes: 201,
    commentCount: 38,
    reporter: "NS",
    isAnonymous: false,
    createdAt: "2026-02-05T15:00:00Z",
    resolvedAt: "2026-02-19T09:00:00Z",
    resolvedBy: "reporter",
    severityScore: 7,
  },
]

export const mockComments: Comment[] = [
  {
    id: "c1",
    issueId: "CL-2024-001",
    text: "I almost damaged my car here yesterday. This needs urgent repair!",
    author: "Anonymous",
    isAnonymous: true,
    createdAt: "2026-02-21T08:30:00Z",
  },
  {
    id: "c2",
    issueId: "CL-2024-001",
    text: "CMC was notified last week but no action taken yet.",
    author: "PK",
    isAnonymous: false,
    createdAt: "2026-02-21T07:45:00Z",
  },
  {
    id: "c3",
    issueId: "CL-2024-001",
    text: "Same issue reported 3 months ago and was fixed temporarily. Poor quality work.",
    author: "Anonymous",
    isAnonymous: true,
    createdAt: "2026-02-20T22:00:00Z",
  },
]

export const emergencyContacts: EmergencyContact[] = [
  { id: "e1", organization: "Colombo North Police Station", district: "Colombo", phone: "011-2421111", serviceType: "police", is247: true },
  { id: "e2", organization: "Colombo South Police Station", district: "Colombo", phone: "011-2432222", serviceType: "police", is247: true },
  { id: "e3", organization: "National Hospital Colombo", district: "Colombo", phone: "011-2691111", serviceType: "medical", is247: true },
  { id: "e4", organization: "Colombo General Hospital", district: "Colombo", phone: "011-2693184", serviceType: "medical", is247: true },
  { id: "e5", organization: "CEB - Colombo Region", district: "Colombo", phone: "011-2343222", serviceType: "utilities", is247: false },
  { id: "e6", organization: "NWSDB - Colombo", district: "Colombo", phone: "011-2636449", serviceType: "utilities", is247: false },
  { id: "e7", organization: "Colombo Municipal Council", district: "Colombo", phone: "011-2686827", serviceType: "government", is247: false },
  { id: "e8", organization: "Kandy Municipal Council", district: "Kandy", phone: "081-2222275", serviceType: "government", is247: false },
  { id: "e9", organization: "Kandy Police Station", district: "Kandy", phone: "081-2222222", serviceType: "police", is247: true },
  { id: "e10", organization: "Kandy General Hospital", district: "Kandy", phone: "081-2222261", serviceType: "medical", is247: true },
  { id: "e11", organization: "Galle Police Station", district: "Galle", phone: "091-2234036", serviceType: "police", is247: true },
  { id: "e12", organization: "Galle General Hospital", district: "Galle", phone: "091-2232276", serviceType: "medical", is247: true },
]

export const nationalHotlines: NationalHotline[] = [
  { name: "Police", number: "119", icon: "shield" },
  { name: "Ambulance", number: "1990", icon: "ambulance" },
  { name: "Fire", number: "110", icon: "flame" },
  { name: "CEB", number: "1987", icon: "zap" },
  { name: "NWSDB", number: "1938", icon: "droplets" },
]
